name: agent-terminal-go-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Create "fake" key/pair
      run: touch connection.crt && touch connection.key
        
    - name: Build Agent
      run: go build -v ./agent.go
        
    - name: Build Terminal
      run: go build -v ./terminal.go
